BAD_NAME_SHORT_LINK = 'Указано недопустимое имя для короткой ссылки'
CREATE = 'СОЗДАТЬ'
GENERATE_ERROR = 'Не удалось сгенерировать уникальный короткий идентификатор.'
ID_NOT_FOUND = 'Указанный id не найден'
LENGHT_SHORT = 6
LONG_LINK = 'Введите длинную ссылку'
MAX_ATTEMPTS = 10
MESSAGE_FOR_SHORT_LINK = 'Предложенный вариант короткой ссылки уже существует.'
MISSING_REQUEST = 'Отсутствует тело запроса'
ORIGINAL_MAX_LENGTH = 500
REDIRECT_SHORT_URL = 'redirect_short_url'
REQUIRED_FIELD = 'Обязательное поле'
SHORT_LINK = 'Введите вашу короткую ссылку'
SHORT_MAX_LENGTH = 16
TOO_LONG_LINK = 'Длина больше {SHORT_MAX_LENGTH} символов'
URL_MISSING = '"url" является обязательным полем!'
WRONG_URL = 'Провертье вводимый адрес'